let page = 1, total = 0, currentCode = null, currentJobId = null, currentRunId = null;
const size = 50;
const text = (value) => value === null || value === undefined ? '-' : value;
const money = (value) => value === null || value === undefined ? '-' : `${(value / 100000000).toFixed(2)} 亿`;
const api = (path, options) => fetch(`/api/v1${path}`, options).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || '请求失败'); return data; });
function view(name) { ['market', 'detail', 'watchlist'].forEach((item) => document.querySelector(`#${item}-view`).hidden = item !== name); }
async function load() { const q = document.querySelector('#search').value.trim(); const params = new URLSearchParams({ page, size, q, sort: 'turnover', order: 'desc' }); const data = await (await fetch(`/api/v1/quotes?${params}`)).json(); total = data.total; document.querySelector('#quotes').innerHTML = data.items.map((item) => `<tr data-code="${item.stock_code}"><td>${item.stock_code}</td><td>${item.name}</td><td>${text(item.market)}</td><td>${text(item.price)}</td><td class="${item.change_pct >= 0 ? 'up' : 'down'}">${text(item.change_pct)}%</td><td>${money(item.turnover)}</td></tr>`).join('') || '<tr><td colspan="6">暂无可展示行情。请先运行 collect-once。</td></tr>'; document.querySelectorAll('#quotes tr[data-code]').forEach((row) => row.onclick = () => detail(row.dataset.code)); document.querySelector('#page').textContent = `第 ${page} 页，共 ${total} 条`; document.querySelector('#previous').disabled = page === 1; document.querySelector('#next').disabled = page * size >= total; }
function chart(bars) { const canvas = document.querySelector('#chart'); const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height); if (!bars.length) return; const values = bars.flatMap((bar) => [bar.high, bar.low]).filter((value) => value !== null); const min = Math.min(...values), max = Math.max(...values), width = canvas.width / bars.length; bars.forEach((bar, index) => { const y = (value) => canvas.height - 20 - ((value - min) / (max - min || 1)) * (canvas.height - 40); const up = bar.close >= bar.open; ctx.strokeStyle = up ? '#fb7185' : '#34d399'; ctx.fillStyle = ctx.strokeStyle; const x = index * width + width / 2; ctx.beginPath(); ctx.moveTo(x, y(bar.high)); ctx.lineTo(x, y(bar.low)); ctx.stroke(); const top = y(Math.max(bar.open, bar.close)); ctx.fillRect(x - Math.max(1, width * .3), top, Math.max(2, width * .6), Math.max(1, Math.abs(y(bar.open) - y(bar.close)))); }); }
function renderResearch(data) { const dims = Object.entries(data.dimensions || {}).map(([name, item]) => `<p><b>${name}</b>：${item ? `${item.stance} / ${item.score}分 — ${item.summary}` : '暂无'}</p>`).join(''); const decision = data.decision ? `<p><b>决策</b>：${data.decision.rating}（信心 ${(data.decision.confidence * 100).toFixed(0)}%）— ${data.decision.advice_one_liner}</p>` : ''; const reruns = data.rerun_dimensions || []; const lineage = `<p class="research-lineage">当前报告：${data.parent_run_id ? '反馈版' : '首次研究'} · ${text(data.created_at || '')}<br>编号：${text(data.short_id || data.run_id?.slice(0, 8))}${data.parent_run_id ? ` · 基于 ${data.parent_run_id.slice(0, 8)}` : ''}${reruns.length ? ` · 重跑：${reruns.join('、')}` : ''}</p>`; document.querySelector('#research-result').innerHTML = `${lineage}<p><b>意图理解</b>：${data.intent?.effect || 'none'}</p>${dims}${decision}`; currentRunId = data.run_id; }
async function pollResearch(jobId) { try { const job = await api(`/research/jobs/${jobId}`); document.querySelector('#research-status').textContent = { queued: '排队中', running: '研究中', success: '研究完成', failed: `失败：${job.error || '未知错误'}` }[job.status] || job.status; if (job.status === 'success') { if (job.run_id) renderResearch(await api(`/research/runs/${job.run_id}`)); await loadHistory(currentCode); return; } if (job.status !== 'failed') setTimeout(() => pollResearch(jobId), 2500); } catch (error) { document.querySelector('#research-status').textContent = error.message; } }
async function startResearch() { try { const data = await api('/research/jobs', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({stock_code: currentCode, prompt: document.querySelector('#research-prompt').value || 'none'}) }); currentJobId = data.job_id; pollResearch(currentJobId); } catch (error) { document.querySelector('#research-status').textContent = error.message; } }
async function sendFeedback() { if (!currentJobId || !currentRunId) { document.querySelector('#research-status').textContent = '暂无可反馈的研究结果'; return; } try { const data = await api(`/research/jobs/${currentJobId}/feedback`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({prompt: document.querySelector('#feedback-prompt').value}) }); currentJobId = data.job_id; pollResearch(currentJobId); } catch (error) { document.querySelector('#research-status').textContent = error.message; } }
async function detail(code) { currentCode = code; currentJobId = null; currentRunId = null; view('detail'); const [quote, bars, notices, current] = await Promise.all([api(`/quotes/${code}`), api(`/bars/${code}`), api(`/notices/${code}`), api(`/research/stocks/${code}/current`).catch(() => null)]); const item = quote.item; document.querySelector('#detail').innerHTML = `<h2>${item.name} <small>${code}</small></h2><p class="price">${text(item.price)} <span class="${item.change_pct >= 0 ? 'up' : 'down'}">${text(item.change_pct)}%</span></p><button id="watch">加入自选</button>`; document.querySelector('#watch').onclick = async () => { await api(`/watchlist/${code}`, { method: 'PUT' }); document.querySelector('#watch').textContent = '已加入自选'; }; if (!bars.items.length && !notices.items.length) await api(`/stocks/${code}/refresh-request`, { method: 'POST' }); chart(bars.items); document.querySelector('#notices').innerHTML = notices.items.map((notice) => `<li>${text(notice.published_at)} ${notice.url ? `<a href="${notice.url}" target="_blank">${notice.title}</a>` : notice.title}</li>`).join('') || '<li>暂无公告，已加入后台采集队列。</li>'; document.querySelector('#research-status').textContent = current ? '已有研究结果' : ''; if (current) { renderResearch(current); currentRunId = current.run_id; currentJobId = current.job_id; } await loadHistory(code); }
async function loadHistory(code) { const data = await api(`/research/stocks/${code}/history`); document.querySelector('#research-history').innerHTML = `<h3>研究历史</h3>` + data.items.map((item) => `<p>${item.created_at} · ${item.kind === 'feedback' ? '反馈版' : '首次研究'} · 编号 ${item.run_id?.slice(0, 8) || '-'}：${item.status}${item.run_id ? ` <button class="history-view" data-run-id="${item.run_id}">查看此版本</button>` : ''}</p>`).join(''); document.querySelectorAll('.history-view').forEach((button) => button.addEventListener('click', () => loadRun(button.getAttribute('data-run-id')))); }
async function loadRun(runId) { const data = await api(`/research/runs/${runId}`); renderResearch(data); currentRunId = runId; document.querySelector('#research-status').textContent = `已切换到历史报告：${runId}`; document.querySelector('#research-result').scrollIntoView({behavior: 'smooth', block: 'start'}); }
async function loadWatchlist() { view('watchlist'); const data = await api('/watchlist'); document.querySelector('#watchlist').innerHTML = data.items.map((item) => `<p><button class="stock" data-code="${item.stock_code}">${item.stock_code} ${text(item.name)}</button> ${text(item.price)} <span class="${item.change_pct >= 0 ? 'up' : 'down'}">${text(item.change_pct)}%</span></p>`).join('') || '<p>尚未加入自选股。</p>'; document.querySelectorAll('.stock').forEach((button) => button.onclick = () => detail(button.dataset.code)); }
async function loadStatus() { const status = await (await fetch('/api/v1/meta/ingest')).json(); const asOf = status.quotes_as_of ? new Date(status.quotes_as_of).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '暂无成功采集'; document.querySelector('#status').textContent = status.stale ? `数据可能过期，最近成功：${asOf}` : `数据截至：${asOf}，覆盖 ${status.stock_count} 只股票`; document.querySelector('#status').className = status.stale ? 'stale' : ''; }
document.querySelector('#refresh').onclick = () => { page = 1; load(); }; document.querySelector('#search').onkeydown = (event) => { if (event.key === 'Enter') { page = 1; load(); } }; document.querySelector('#previous').onclick = () => { page -= 1; load(); }; document.querySelector('#next').onclick = () => { page += 1; load(); }; document.querySelector('#research-start').onclick = startResearch; document.querySelector('#feedback-send').onclick = sendFeedback; document.querySelectorAll('nav button').forEach((button) => button.onclick = () => button.dataset.view === 'watchlist' ? loadWatchlist() : view('market')); document.querySelector('.back').onclick = () => view('market'); loadStatus(); load();
